package day44_Exceptions;

public class CheckedException {
    public static void main(String[] args) {
        System.out.println("Test started");
        //Thread.sleep(3000);//unhandled exception, interrupted
        System.out.println("test completed");//it give us compile error
    }

}
